set shell := ["bash", "-cu"]

init: _create-network
	just redpanda/init
	just redis/init

down:
	just redpanda/down
	just redis/down
	-docker network rm rideshare_network

redpanda-init: _create-network
	just redpanda/init

redpanda-down:
	just redpanda/down

redis-init: _create-network
	just redis/init

redis-down:
	just redis/down

watch:
	docker stats $(docker ps -q --filter network=rideshare_network)

status:
	docker stats $(docker ps -q --filter network=rideshare_network) --no-stream

_create-network:
	-docker network create rideshare_network 2>/dev/null || true
