set shell := ["bash", "-cu"]

init:
	docker compose up -d
	@echo "Redis available at localhost:6379"

watch:
	docker stats $(docker ps -q --filter name=redis-0)

status:
	docker stats $(docker ps -q --filter name=redis-0) --no-stream

down:
	docker compose down --remove-orphans -v

cli:
	docker exec -it redis-0 redis-cli
